# Name of your application. Used to uniquely configure containers.
service: sif_fine_box

# Name of the container image.
image: sif_fine_box

# The Dockerfile to use for building the image.
builder:
  arch: amd64

servers:
  web:
    hosts:
      - 138.68.73.196

proxy:
    host: finebox.sif-holbaek.dk
    ssl: true
    healthcheck:
      interval: 3
      path: /up
      timeout: 3

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: registry.digitalocean.com/sif-container-registry
  username: 'nikodyring@gmail.com'
  password:
    - KAMAL_REGISTRY_PASSWORD # Must be present in your `.env`.
env:
  clear:
    RAILS_SERVE_STATIC_FILES: true
    POSTGRES_USER: "sif_fine_box"
    POSTGRES_DB: "sif_fine_box_production"
    POSTGRES_HOST: "sif_fine_box-db" # With the pattern: <service_name>-<accessory_name>
    REDIS_URL: "redis://sif_fine_box-redis:6379/0" # We need to override the REDIS_URL (used by Sidekiq and your cache_store), same pattern: <service_name>-<accessory_name>
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - SECRET_KEY_BASE

accessories:
  db:
    image: postgres:16
    host: 138.68.73.196
    port: 5432
    env:
      clear:
        POSTGRES_USER: "sif_fine_box"
        POSTGRES_DB: "sif_fine_box_production" # The database will be created automatically on first boot.
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    host: 138.68.73.196
    directories:
      - data:/data
